### PR TITLE
Update solution projects to .NET 8

### PR DESCRIPTION
**Pull request by kvertner**
The UWP project still has some issues.

Appreciate your help!

### CODE REVIEW

**Comment by jefffhaynes** [comment]
UAP can't reference .NET 8 so that's the problem.  Are you trying to use this with UWP, or just maintain support?  I'm probably ok dropping UWP support from the library and just leaving the old version out there if anyone needs it.

**Comment by kvertner** [comment]
We are not using UWP.  So your solution would work perfectly for us!

**Comment by LarryChiem** [comment]
@kvertner Great job on the PR. Looks like this is ready to be merged? @jefffhaynes

**Comment by kvertner** [comment]
@jefffhaynes did you want me to remove the UWP project or were you going to do that?  Sorry for the confusion.

**Comment by jefffhaynes** [comment]
If you can remove the UWP project and the editor from the build that would be great, thanks.

**Comment by LarryChiem** [comment]
What does removing the UWP project and editor mean?

**Comment by kvertner** [comment]
OK @jefffhaynes I think we should be good to go now.  I removed the UWP project from the solution.  I didn't rev any version numbers...not sure how you wanted to handle that.  From my side it looks like everything is building and should be good to go.

**Comment by LarryChiem** [comment]
image

Anyone else see this in the latest commit?

**Comment by jefffhaynes** [comment]
Please just exclude the universal projects from the solution, don't actually delete the code from the branch.

**Comment by jefffhaynes** [comment]
Please change the package release notes to indicate the upgrade and removal of UWP and make this version 2.0.0 for the package and files.

**Comment by kvertner** [comment]
Classic Tester 1.0.0.0 --> 2.0.0.0
Classic 5.3.3.2 --> 6.0.0.0
Core 1.6.6 --> 2.0.0
Utility 1.0.0.0 --> 2.0.0.0

@jefffhaynes I'm not 100% clear on what you mean by "package release notes".  There is the readme.md file..should I add release notes there?

**Comment by LarryChiem** [comment]
image
Does XBee get updated from 5.3.3 as well? @jefffhaynes 
Oh sorry, maybe I jumped the gun and you're mid-process updating that. I saw your comment 'Classic 5.3.3.2 --> 6.0.0.0'

**Pull request merged**
